platform :ios, '13.0'

target 'DemoApp' do
  use_frameworks!

  pod 'PersonaInquirySDK2', '~>2.18.0'
  pod 'PersonaNfc', '~>2.18.0'
  pod 'PersonaWebRtc', '~>2.18.0'
  pod 'Persona-OpenSSL-Universal', '=1.0.0'
  pod 'WebRTC-lib', '=111.0.0'

end
